// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvrdtu4dn4VLMz5kUxIUfIlp9GfjmxpEvXYipYtT9sVebIgckvCCQkwAGhbE+t5+h59si5ceJFIKbKb",
	"SadrJX9MgQSwsS/fviFfcMiTlDNgSuLuF5wSQRJQIMyvPlFkRiQMozFRSz0SgQwFTRXlDHfxDaOfM0A0",
	"AqbonIJAcy6QWgKK3EzsYXggSRoD7uJk5VfGqV4h1et6mJFEf5C//Ugj7GEBnzMqIMJdJTLwsAyXkBBL",
	"pVIg9PzfPxD/j7b/5vaFe/Bvv7S91511Pv7yX/+GPaxWqV5fKkHZAq/X63y1jWPWD5i/QQIkz0SoH1IB",
	"Up+XLRApzokok4qwUB8sFTwFoSiYxUMBRMFHRZOG9Sc0AalIkqL7JbANzqF7IpGdrJkx5yIhyvIIfLOa",
	"5hCJ3rN4lXNo65geptFzhFY9zC7pJeThAthCa8XrYw8nlOU/O97T5fPVgySgiN5dH+dvAua4i38KStUN",
	"nDSDXGCX+fdrz+pYjQ1XuUT16wo3Ns6cH1gGm6f/Kr0SxB0N4aN9sb33tX2L9NutrVmW4O6HYmN827R4",
	"CuGhjLjW3+o5iqjMKCSJ4/dz3P1w4Hw7b327fei1h7M0er5qx0QqZFd4rn6vqxjxwbKloiol6/jsnxAq",
	"7OEHn0Dq58ZcgRJZZboMvlSQaK0XSuNMkLiqEdjDkrJFFhNRGS6xJmTpolAZ3+mDnwp+RyMQrShMWpQH",
	"xTx9mJzn5+MbI6goopqZJB5XEMVyYpPX5+MbROKYh0QPGHsGEi41WMU0JIgyFHIBEnGBEhrH1P56Aa1F",
	"y0NTfDTF+s9pu51M8csahCXkoS7fS/JAkywx+95DhDQNz93476f5xqXp6TG8CSUd/83tBw0aPydNqG5Q",
	"qIFQygyhi4wIwhQ8l9bONpNKWvXY02jdUl1NuMHUutJW9GLAFpTt81JgPrAkoylOuVQLAfJz7Ah24FKO",
	"N8JLvtwFlaq+2ZgsKNNGi2IqFeLzutuQNQ1i8KA+pmQBHxX/BA1CmuhhIxMBSlC40+5VY4aeifRMvZMA",
	"mcVKNok+f9X9gqmCRB6Kj3quW4wIQVZGNDslcAkJF6unGaeds88+n2dwiV23psf3VC1RxqiqqO7bM6e8",
	"naPLM2fijcr64vLs8e3Z4+Ts8ZKePb6lZ48Tevbyf2Vs/7d0PsvQLivRxo6oIfcy5ly5C7fyrYkzJjOI",
	"5W6t+VJn7ha+Z1LxBH2ClX9H4kzHLFRIG7eRxcKEoixCcxorMCs0nM2G2DvPo19vhiJPj/B89/Tz3uDb",
	"kiJTEjbQ849sBoKBAomKr3QAIcoQXCIioBIZPy1IMGzYJ/sRqHsuPj3Nxt0kFHI2p4tMNOtBykUToHKh",
	"jCgLHFXcYCswxJ22apvC3denp8enRhL2d6c4BmUKFiD0Oe6opDMaU7Xa4ygqH5VuQS8iGImNa3OPt038",
	"3Mm7K2vacm8iZa0/5BlTuOkA5WJO3s+IhVgBO0XiFnImlSCUqbp7CtPsUH+hYzOTj+SO4LBsxHxtwnAu",
	"yAIOjt7d59tarAkuiNinzdcuVdghDR0yF7hlEZmyNFNoTiGOLMIYS2tS55AzBqF+9dEpR22jQqXLb9HN",
	"1RC9ECBTziT4nMWrl60p+9XE/100zdrt49DwAcwzdIPADmZS62QxbAdTIuU9F5Ed/MUOLrlU9S+5UHbA",
	"rZcTZwenbJCkaoUypmi8lQ5LJDLGKFu0pmwj8CsjqW4QkDTtyuNQgPpFh/4zX9y3inShJe/C7unJ8ZH+",
	"DNcA9NZB5quWf/tzNwg+/B78cvuqa//88uH3bqB/aUx9FbReHZQyQxEtHqJpLrbU6FwC4CETc7xcG/Uw",
	"yc3HJXXlpMPN9n1qv0P5In6um8ishuaCJ0YsIVEk5gv0goQhpAoiDzGuEAl1TJqlnL1scn+iAk2HHKuA",
	"Mhtblkh02OR8ggZkENKc8bC5v7nPt03eibNKzV7DL/L97VBCCGAK2XqADqp3Vn6cWxgPRv3h6C328NXN",
	"aGSffu0NLwZ97OGb0T9G7/99hD3cH1wMJoP+3oziukS/rYKIfbE3iS3ixWpO1m7nIePR5FsFttuS2ONG",
	"7RdFwtX5F0tLTBRIZcmpLT8QgouGSOzXc/Tm5PTvSOtGTAlTCPSXKIdK9GIs+CyGBPVBERpbdH43mYxR",
	"bzyUGkSnrA9zyiDSVmQ+1bvL7pQ9oskqBYO9j2hCVQzo0c61ioIep+zRL/49bv11v/Q6rVYrcKvLgLI7",
	"EtPIJ2KRJVqtHtHQDqHK0Em7jepzGVf+nGcsQo9oxHUIZJ9P2icNX5NYA97KhwcqlUSPqGcHUDFw0n7T",
	"MC8FkVCppeRHwCjoHcbFGCrGTtrHDbMzRjK11EFxaFLeR3RTGzlpd1ATZ2wEZTjiHq9B3IFARgHQIzpt",
	"ZEvGyB2hMZkZEeWVws3RU0tsJVDr81Du1qku2qs62MOZiHEXL5VKZTcwVSklSPgJRIuCmre4WAQRD4Ol",
	"SuJAzEO9qEP8SkAQmcXrZLzLEsKQFpehHx7SmDBr5QXIK47UkkrEw9AgVAhNtmMs4qswPLBfrT1cwFm9",
	"Cn41RALmYLZyFXAqS3qs7W1QU5QoM0H9Ym4TmSk34q/v+m/X70dobN+iuSALYyGVUvwLLbLXb9od9N//",
	"9folsmjoSiHaG4BUaMajlQ3QkFoShUKSSYgs/YZsDzk8+inQ5wkKjxGEaRYklE1xC/VmUu9dFGftgUPC",
	"tDOdASJKCTrLtI4rjgiSlC3iRiJ0AiytD0bG9q1ozYI2YCo490/JmZ9zp6myvcNrGVV1Livk0YY0KFOd",
	"19U06fTNm2qS1G43ZRlKY2CDI1pyoTy01BrrFxorsyQhYtVEcXOBf1O7nHxXuSAtq83M0s0Wthcmfiq4",
	"9uetBVXLbNaifDfiYu/QmQXeHj5lE3QPn1cD3cOnbiHu4RMr2evhW+WYqqOWA83bww++lpl/R0w2YjoH",
	"w9FvvYthv3f19uZyMJpgD4/eT359fzPSMVLv4mrQ6//n4D+G15Nr7OHx4OpyeH09fD/qD0ZDF0b1bibv",
	"BqPJ8Lw3MSPD0WRwNepd2Je/9YYXvbOLAb7dDgudFll1bgoIDRj2dyDzkEX0jkYZiWuWa+ItyhBBSRYr",
	"6m8GI/hJ2O83Yr+JPams7fwDUb8Zom4pixPSTjVpQN6x7XYjnae7o91z0yLhApAkCfimi7lNpvPkrSkb",
	"6CAemBIrZJeegUScbUyZExpnAlpoBDpCAp2Je4jpH1Nm+eSbJVpowlM/hjuIkT0Ngs8ZiaXh+JwKqdxe",
	"2qXPSPjpnohoynSUQJSreVkWHtQmqFqPrXkP7bSj7baBh98BiZs6zXY8d1/2NIqzojRVrxM2NqzPCeOM",
	"hjpFJmqZZ26VRcqyxNJSckifepfDrdJc9VJmXHvCjOXPt/Wtn+Aqiwp0QzO8WPWwZmpx7J1Q/lV+ZGlz",
	"N/saQs4iIz1N6hKQI6KoV2heCeuxCrqPX+vgY8em1ZrtrkzzenuTWUbjKM87N1jUabVb7SeXw537KOTs",
	"7uOUGziGPLmX7mRRbZ3bobxxbmyguNpTdtILIT6pj+5mrc3VHsrm3BUoFQlNyd1dMOqfX+pUyJ1gM+lx",
	"EULIk2rgEOzfv96r0VvUdEODUUIYMa2aoiaIKEOVhkcYZ1KBkOiOkik7j3kWjYiidzB+25qyiXZGvfEQ",
	"zXkc83uJegMTErOIiLxSy5k0fYNwhUgouJSoQo20sBfTEJi96+SY0ktJuAR0ZNRnkyf39/ctYl6bFNDN",
	"lcHF8Hwwuh74R612S+eElYgabxCOilpJrsrjnCe98bCiabkCrz3MU2AkpbiLj1vt1onTSgNSAUlpcNch",
	"cboknaC8i9H9ghegmsDFNJMBkVq3WtqCUmrb2SYXzVLToTEU2BbOMMJdfEGl6leufVTvyH3Y1aVlWTID",
	"4ZrWrm+lOBKgMsGQiauc/0/JorgO9zkDk2Y4ySTkwXbNJf3DmGlxAy6COclihbun7c1U6Piomgp12hqA",
	"9jWM1l5zK56yiFYiJQNu+ocJNYobY3tor3T7q4Rvw5G5V2RjSiPGo3Y7N12d3XS/YJKa+p+mLtDRjh4r",
	"1zukpGouMhhk2ELXLAxBynkWx6v83gFEpYZoZTzZS4/LJV49jS5bAWwg6IxEeTho9+58v717ZdpFTXDi",
	"nISh4/j70VErzmkKTr+nFIp6nbT1OnAfejivA1hMQFVQUGRh/F45dmvSlqYrNOemd40IYnDfWHrfxB/7",
	"eb+8YbYXgIpGShhTYCpvo0CEhv3aTc8WGs5NnuE8VeRNWR7cgE4B4xgtgGlqABGGhn1TZb6yyqFTLen8",
	"kXZHfufoCBXx3LCPfJQ7EgJpK4K7oHN0FPyUI6JPo61+WrLyo9kOQDF3gkvRftsLqI2wZAzxjEerb45I",
	"Vu02Lziva0jY+ZP23dHNcFcqkKzA4g8I/KtA4En7zfej4JyzeUxDhfwygDPhkgEHkrj7QmSjB/OXBGqH",
	"tRX0bELqtbcrtMwziz0RZiaYLT8sNxJ9l6C76LuG6m9BvSvT9D8pAnpXpEXejsySSpSn7JuMcxWA8yWE",
	"nypccyvuZdnm7WnDshhU08VVM65D4bzt8nVvaOfs9oZN7Cg/Cbb+S0tD/Hmy5xqLPUgTRP6AqZyCk+9H",
	"QYFNLO8f/yUxyKn5VzDI+2oKu9tK0GyFhv0mjPkTDaX9fcOTMkH7EaD8sPz/H5b/FtRXQw/3v8Was7nz",
	"0b4aWlGvC4x9uuV31PJD7clRARCyzKzyKMHbedEppnMIV2EMtoppMr/GpcqTrW/X/xMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
